language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - ES_VERSION=5.6.5
        - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
        - ELASTICA_VERSION=^5.0
    - php: 7.3
      env:
        - ES_VERSION=6.3.0
        - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
        - ELASTICA_VERSION=^6.0

install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &

before_script:
    - composer self-update
    - composer require ruflin/elastica ${ELASTICA_VERSION}
    - composer install

script:
    - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
    - if [[ "$TRAVIS_PHP_VERSION" == "7.3" && "$ES_VERSION" == "6.3.0" ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_success:
    - if [ -f coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
